'use client';

import { useQuery, useMutation } from "convex/react";
import { api } from "@convex/_generated/api";
import { useState } from "react";
import { FileText, Plus, CheckCircle, Loader2, PenTool } from "lucide-react";
import { jsPDF } from "jspdf";
import { useParams } from "next/navigation";
import { Id, Doc } from "@convex/_generated/dataModel";
import { logError } from "@/lib/errorTracking";

export default function LegalPage() {
  const params = useParams();
  const projectId = params.id as Id<"projects">;
  
  const docs = useQuery(api.legal.getDocs, { projectId });
  const generateUploadUrl = useMutation(api.legal.generateUploadUrl);
  const createDoc = useMutation(api.legal.createDoc);
  const signDoc = useMutation(api.legal.signDoc);

  const [isGenerating, setIsGenerating] = useState(false);
  const [showModal, setShowModal] = useState(false);
  
  // Form State
  const [docType, setDocType] = useState<"SAFE" | "NDA">("SAFE");
  const [investorName, setInvestorName] = useState("");
  const [amount, setAmount] = useState("");

  const handleGenerate = async () => {
    setIsGenerating(true);
    try {
      // 1. Generate PDF with jsPDF
      const doc = new jsPDF();
      
      // Header
      doc.setFontSize(20);
      doc.text(docType === "SAFE" ? "Simple Agreement for Future Equity" : "Non-Disclosure Agreement", 105, 20, { align: "center" });
      
      // Content
      doc.setFontSize(12);
      doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 40);
      
      if (docType === "SAFE") {
        doc.text(`Investor: ${investorName}`, 20, 50);
        doc.text(`Investment Amount: $${amount}`, 20, 60);
        doc.text(`Valuation Cap: $5,000,000`, 20, 70);
        doc.text(`Discount Rate: 20%`, 20, 80);
        doc.text(`\nThis agreement certifies that the Investor has purchased the right to certain shares...`, 20, 90, { maxWidth: 170 });
      } else {
        doc.text(`Party A: VentureDeck Project`, 20, 50);
        doc.text(`Party B: ${investorName}`, 20, 60);
        doc.text(`\nThe parties agree to keep all confidential information strictly private...`, 20, 80, { maxWidth: 170 });
      }

      // Footer
      doc.text("Generated by VentureDeck Legal Automation", 105, 280, { align: "center" });

      const pdfBlob = doc.output("blob");

      // 2. Upload to Convex Storage
      const postUrl = await generateUploadUrl();
      const result = await fetch(postUrl, {
        method: "POST",
        headers: { "Content-Type": "application/pdf" },
        body: pdfBlob,
      });
      const { storageId } = await result.json();

      // 3. Save Metadata
      await createDoc({
        projectId,
        type: docType,
        storageId,
      });

      setShowModal(false);
      setInvestorName("");
      setAmount("");
    } catch (error) {
      logError(error, { component: 'LegalPage', action: 'generateDocument' });
    } finally {
      setIsGenerating(false);
    }
  };

  const handleSign = async (docId: Id<"legalDocs">) => {
    await signDoc({ docId });
  };

  if (!docs) return <div className="p-10 flex justify-center"><Loader2 className="animate-spin text-primary" /></div>;

  return (
    <div className="p-8 max-w-5xl mx-auto bg-background text-foreground min-h-screen">
      <header className="mb-8 flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-foreground mb-2">Legal Center</h1>
          <p className="text-muted-foreground">Manage your SAFEs, NDAs, and contracts.</p>
        </div>
        <button
          onClick={() => setShowModal(true)}
          className="px-5 py-2.5 bg-primary hover:bg-primary/90 text-primary-foreground rounded-xl font-medium flex items-center gap-2 transition-all shadow-lg shadow-primary/20"
        >
          <Plus className="w-4 h-4" /> Generate Document
        </button>
      </header>

      <div className="grid gap-4">
        {docs.length === 0 ? (
          <div className="text-center py-20 bg-muted/20 rounded-2xl border border-border">
            <FileText className="w-12 h-12 text-muted-foreground mx-auto mb-4" />
            <p className="text-muted-foreground">No documents generated yet.</p>
          </div>
        ) : (
          docs.map((doc: Doc<"legalDocs"> & { url: string | null }) => (
            <div key={doc._id} className="glass-panel p-6 rounded-xl flex items-center justify-between group hover:border-primary/30 transition-all">
              <div className="flex items-center gap-4">
                <div className={`w-12 h-12 rounded-lg flex items-center justify-center ${doc.status === 'signed' ? 'bg-emerald-500/20 text-emerald-400' : 'bg-muted text-muted-foreground'}`}>
                  <FileText className="w-6 h-6" />
                </div>
                <div>
                  <h3 className="text-lg font-bold text-foreground">{doc.type} Agreement</h3>
                  <p className="text-sm text-muted-foreground">Created {new Date(doc.createdAt).toLocaleDateString()}</p>
                </div>
              </div>

              <div className="flex items-center gap-4">
                {doc.status === "signed" ? (
                  <div className="flex items-center gap-2 text-emerald-400 bg-emerald-500/10 px-3 py-1.5 rounded-lg border border-emerald-500/20">
                    <CheckCircle className="w-4 h-4" />
                    <span className="text-sm font-bold">Signed</span>
                  </div>
                ) : (
                  <button
                    onClick={() => handleSign(doc._id)}
                    className="flex items-center gap-2 text-amber-400 bg-amber-500/10 px-3 py-1.5 rounded-lg border border-amber-500/20 hover:bg-amber-500/20 transition-colors"
                  >
                    <PenTool className="w-4 h-4" />
                    <span className="text-sm font-bold">Sign Now</span>
                  </button>
                )}
                
                {doc.url && (
                  <a 
                    href={doc.url} 
                    target="_blank" 
                    rel="noopener noreferrer"
                    className="text-sm text-muted-foreground hover:text-foreground underline"
                  >
                    View PDF
                  </a>
                )}
              </div>
            </div>
          ))
        )}
      </div>

      {/* Generation Modal */}
      {showModal && (
        <div className="fixed inset-0 bg-black/80 backdrop-blur-sm flex items-center justify-center z-50 p-4">
          <div className="bg-card border border-border w-full max-w-md rounded-2xl p-6 shadow-2xl">
            <h2 className="text-xl font-bold text-foreground mb-6">Generate Legal Document</h2>
            
            <div className="space-y-4">
              <div>
                <label className="block text-sm text-muted-foreground mb-1">Document Type</label>
                <div className="flex gap-2">
                  <button 
                    onClick={() => setDocType("SAFE")}
                    className={`flex-1 py-2 rounded-lg border transition-all ${docType === "SAFE" ? "bg-primary/20 border-primary text-primary" : "bg-muted border-border text-muted-foreground"}`}
                  >
                    SAFE
                  </button>
                  <button 
                    onClick={() => setDocType("NDA")}
                    className={`flex-1 py-2 rounded-lg border transition-all ${docType === "NDA" ? "bg-primary/20 border-primary text-primary" : "bg-muted border-border text-muted-foreground"}`}
                  >
                    NDA
                  </button>
                </div>
              </div>

              <div>
                <label className="block text-sm text-muted-foreground mb-1">Investor / Counterparty Name</label>
                <input 
                  type="text" 
                  value={investorName}
                  onChange={(e) => setInvestorName(e.target.value)}
                  className="w-full bg-input border border-border rounded-lg px-4 py-2 text-foreground focus:border-primary outline-none"
                  placeholder="e.g. John Doe Ventures"
                />
              </div>

              {docType === "SAFE" && (
                <div>
                  <label className="block text-sm text-muted-foreground mb-1">Investment Amount ($)</label>
                  <input 
                    type="number" 
                    value={amount}
                    onChange={(e) => setAmount(e.target.value)}
                    className="w-full bg-input border border-border rounded-lg px-4 py-2 text-foreground focus:border-primary outline-none"
                    placeholder="50000"
                  />
                </div>
              )}
            </div>

            <div className="mt-8 flex gap-3">
              <button 
                onClick={() => setShowModal(false)}
                className="flex-1 py-2.5 rounded-xl text-muted-foreground hover:bg-muted/20 transition-colors"
              >
                Cancel
              </button>
              <button 
                onClick={handleGenerate}
                disabled={isGenerating || !investorName}
                className="flex-1 py-2.5 bg-primary hover:bg-primary/90 text-primary-foreground rounded-xl font-bold flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {isGenerating ? <Loader2 className="w-4 h-4 animate-spin" /> : "Generate PDF"}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
